function content(){
    let fname;
    fname=document.getElementById("fname").value;
    console.log(fname);
    let lname;
    lname=document.getElementById("lname").value;
    console.log(lname);
    document.getElementById("name").innerHTML=fname+lname;
    let email;
    email=document.getElementById("email").value;
    console.log(mail);
    document.getElementById("mail").innerHTML=email;
    conno=document.getElementById("conno").value;
    console.log(conno);
    document.getElementById("con").innerHTML=conno;
    aadhar=document.getElementById("aadhar").value;
    console.log(aadhar);
    document.getElementById("aadh").innerHTML=aadhar;
    let add1;
    add1=document.getElementById("add1").value;
    console.log(add1);
    let add2;
    add2=document.getElementById("add2").value;
    console.log(add2);
    document.getElementById("add").innerHTML=add1+add2;
    city=document.getElementById("city").value;
    console.log(city);
    document.getElementById("ci").innerHTML=city;
    state=document.getElementById("state").value;
    console.log(state);
    document.getElementById("st").innerHTML=state;
    pincode=document.getElementById("pincode").value;
    console.log(pincode);
    document.getElementById("pin").innerHTML=pincode;
    let date;
    date=document.getElementById("date").value;
    console.log(date);
    let month;
    month=document.getElementById("month").value;
    console.log(month);
    let year;
    year=document.getElementById("year").value;
    console.log(year);
    document.getElementById("dob").innerHTML=date+month+year;
    degree=document.getElementById("degree").value;
    console.log(degree);
    document.getElementById("deg").innerHTML=degree;
    inter=document.getElementById("inter").value;
    console.log(inter);
    document.getElementById("int").innerHTML=inter;
    ssc=document.getElementById("ssc").value;
    console.log(ssc);
    document.getElementById("sc").innerHTML=ssc;
    gender=document.getElementById("gender").value;
    console.log(gender);
    document.getElementById("gen").innerHTML=gender;
}